apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-pod
spec:
  containers:
  - name: phpinfo-container
    image: academiaonline/simplilearn-phpinfo:latest
    command:
      - "php"
    args:
      - "-f"
      - "index.php"
      - "-S"
      - "0.0.0.0:8080"
